spring:
  application:
    name: music-app
  datasource:
    url: jdbc:mysql://localhost:3306/music_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: admin